name: Build and Release sshg

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build:
    name: Build binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v1.9.0
        with:
          rust-version: stable

      - name: Build
        run: cargo build --release

      - name: Package Binary and Generate Checksum
        run: |
          mkdir -p dist
          OS=$(echo "${{ matrix.os }}" | cut -d'-' -f1)
          FILENAME="sshg-${OS}"
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            cp target/release/sshg.exe sshg.exe
            7z a dist/${FILENAME}.zip sshg.exe
            sha256sum sshg.exe > dist/${FILENAME}.sha256.txt
          else
            cp target/release/sshg sshg
            chmod +x sshg
            zip -j dist/${FILENAME}.zip sshg
            sha256sum sshg > dist/${FILENAME}.sha256.txt
          fi
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-zip
          path: dist/*

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
