name: Rust

on:
  push:
    tags:
      - 'v*'
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
      - name: Build
        run: cargo build --release
        
      - name: Package Binary and Generate Checksum
        run: |
          mkdir -p dist
          cp target/release/sshg sshg
          chmod +x sshg
          zip -j dist/sshg-linux.zip sshg
          sha256sum sshg > dist/sshg-linux.sha256.txt
          
      - name: Upload Artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts
          path: dist/*

  release:
    name: Create Release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-artifacts
          path: dist
          
      - name: List downloaded files (debug)
        run: |
          echo "Files in dist:"
          ls -la dist/
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASEs_TOKEN }}
