name: Rust

on:
  push:
    tags:
      - 'v*'
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Package Binary and Generate Checksum
      run: |
        mkdir -p dist
        cp target/release/sshg sshg
        chmod +x sshg
        zip -j dist/sshg-linux.zip sshg
        sha256sum sshg > dist/sshg-linux.sha256.txt
    - name: Upload Artifact
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v4
      with:
        name: linux-zip
        path: dist/*

  release:
    name: Create Release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
